Resources:
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.questionTableName}
      AttributeDefinitions:
        - AttributeName: answer 
          AttributeType: S
      KeySchema:
        - AttributeName: answer
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  QuestionPlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.questionPlayerTableName}
      AttributeDefinitions:
        - AttributeName: player_sub_answer 
          AttributeType: S
      KeySchema:
        - AttributeName: player_sub_answer
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  PlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.playerTableName}
      AttributeDefinitions:
        - AttributeName: player_sub 
          AttributeType: S
      KeySchema:
        - AttributeName: player_sub
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      
