Resources:
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.questionTableName}
      AttributeDefinitions:
        - AttributeName: qId 
          AttributeType: S
      KeySchema:
        - AttributeName: qId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      
  PlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.playerTableName}
      AttributeDefinitions:
        - AttributeName: player_sub 
          AttributeType: S
      KeySchema:
        - AttributeName: player_sub
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      
